basePath: /api/v1
definitions:
  api.TheaterRequest:
    properties:
      name:
        minLength: 3
        type: string
    required:
    - name
    type: object
  api.TheaterResponse:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
  middleware.HttpError:
    properties:
      code:
        type: integer
      fields:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API za upravljanje z kinodvoranami in njihovim sporedom
  title: Spored API
  version: "1.0"
paths:
  /theaters:
    get:
      consumes:
      - application/json
      description: List theaters
      operationId: TheatersList
      parameters:
      - default: 10
        description: Limit the number of responses
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset the first response
        in: query
        name: offset
        type: integer
      - description: Sort results
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.TheaterResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.HttpError'
      summary: List theaters
      tags:
      - theaters
    post:
      consumes:
      - application/json
      description: Create theater
      operationId: TheatersCreate
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.TheaterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.TheaterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.HttpError'
      summary: Create theater
      tags:
      - theaters
  /theaters/{id}:
    delete:
      consumes:
      - application/json
      description: Delete theater
      operationId: TheatersDelete
      parameters:
      - description: Theater ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.HttpError'
      summary: Delete theater
      tags:
      - theaters
    get:
      consumes:
      - application/json
      description: Show theater
      operationId: TheatersShow
      parameters:
      - description: Theater ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.TheaterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.HttpError'
      summary: Show theater
      tags:
      - theaters
    put:
      consumes:
      - application/json
      description: Update theater
      operationId: TheatersUpdate
      parameters:
      - description: Theater ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.TheaterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.TheaterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.HttpError'
      summary: Update theater
      tags:
      - theaters
swagger: "2.0"
