apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spored
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - spored.cinecore.timhrovat.com
    secretName: spored-tls
  rules:
  - host: spored.cinecore.timhrovat.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spored
            port:
              number: 8080
